# HTTP Server.
server:
  address:             ":8090"
  dumpRouterMap:       true
  routeOverWrite:      true
  accessLogEnabled:    true
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"
  secretKey:            "qo&l_l&&2ycxa5+yvvuezn1nskyxgi0dgjmpwly#)poc$x)17i"

# Global logging.
logger:
  level : "all"
  stdout: true
  stdoutColorDisabled: true

# Database.
database:
  logger:
    level:   "all"
    stdout:  true

  default:
    link:   "mysql:root:@tcp(127.0.0.1:3306)/blog"
    debug:  true