// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "blog-api/internal/logic/blog"
	_ "blog-api/internal/logic/category"
	_ "blog-api/internal/logic/comment"
	_ "blog-api/internal/logic/middleware"
	_ "blog-api/internal/logic/moment"
	_ "blog-api/internal/logic/tag"
	_ "blog-api/internal/logic/user"
	_ "blog-api/internal/logic/visitor"
)
