// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// About is the golang structure of table about for DAO operations like Where/Data.
type About struct {
	g.Meta `orm:"table:about, do:true"`
	Id     interface{} //
	NameEn interface{} //
	NameZh interface{} //
	Value  interface{} //
}
