// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Blog is the golang structure of table blog for DAO operations like Where/Data.
type Blog struct {
	g.Meta           `orm:"table:blog, do:true"`
	Id               interface{} //
	Title            interface{} // 文章标题
	FirstPicture     interface{} // 文章首图，用于随机文章展示
	Content          interface{} // 文章正文
	Description      interface{} // 描述
	IsPublished      interface{} // 公开或私密
	IsRecommend      interface{} // 推荐开关
	IsAppreciation   interface{} // 赞赏开关
	IsCommentEnabled interface{} // 评论开关
	CreateTime       *gtime.Time // 创建时间
	UpdateTime       *gtime.Time // 更新时间
	Views            interface{} // 浏览次数
	Words            interface{} // 文章字数
	ReadTime         interface{} // 阅读时长(分钟)
	CategoryId       interface{} // 文章分类
	IsTop            interface{} // 是否置顶
	Password         interface{} // 密码保护
	UserId           interface{} // 文章作者
}
