// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure of table comment for DAO operations like Where/Data.
type Comment struct {
	g.Meta          `orm:"table:comment, do:true"`
	Id              interface{} //
	Nickname        interface{} // 昵称
	Email           interface{} // 邮箱
	Content         interface{} // 评论内容
	Avatar          interface{} // 头像(图片路径)
	CreateTime      *gtime.Time // 评论时间
	Ip              interface{} // 评论者ip地址
	IsPublished     interface{} // 公开或回收站
	IsAdminComment  interface{} // 博主回复
	Page            interface{} // 0普通文章，1关于我页面，2友链页面
	IsNotice        interface{} // 接收邮件提醒
	BlogId          interface{} // 所属的文章
	ParentCommentId interface{} // 父评论id，-1为根评论
	Website         interface{} // 个人网站
	Qq              interface{} // 如果评论昵称为QQ号，则将昵称和头像置为QQ昵称和QQ头像，并将此字段置为QQ号备份
}
