// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Friend is the golang structure of table friend for DAO operations like Where/Data.
type Friend struct {
	g.Meta      `orm:"table:friend, do:true"`
	Id          interface{} //
	Nickname    interface{} // 昵称
	Description interface{} // 描述
	Website     interface{} // 站点
	Avatar      interface{} // 头像
	IsPublished interface{} // 公开或隐藏
	Views       interface{} // 点击次数
	CreateTime  *gtime.Time // 创建时间
}
