// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// LoginLog is the golang structure of table login_log for DAO operations like Where/Data.
type LoginLog struct {
	g.Meta      `orm:"table:login_log, do:true"`
	Id          interface{} //
	Username    interface{} // 用户名称
	Ip          interface{} // ip
	IpSource    interface{} // ip来源
	Os          interface{} // 操作系统
	Browser     interface{} // 浏览器
	Status      interface{} // 登录状态
	Description interface{} // 操作描述
	CreateTime  *gtime.Time // 登录时间
	UserAgent   interface{} // user-agent用户代理
}
