// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Moment is the golang structure of table moment for DAO operations like Where/Data.
type Moment struct {
	g.Meta      `orm:"table:moment, do:true"`
	Id          interface{} //
	Content     interface{} // 动态内容
	CreateTime  *gtime.Time // 创建时间
	Likes       interface{} // 点赞数量
	IsPublished interface{} // 是否公开
}
