// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OperationLog is the golang structure of table operation_log for DAO operations like Where/Data.
type OperationLog struct {
	g.Meta      `orm:"table:operation_log, do:true"`
	Id          interface{} //
	Username    interface{} // 操作者用户名
	Uri         interface{} // 请求接口
	Method      interface{} // 请求方式
	Param       interface{} // 请求参数
	Description interface{} // 操作描述
	Ip          interface{} // ip
	IpSource    interface{} // ip来源
	Os          interface{} // 操作系统
	Browser     interface{} // 浏览器
	Times       interface{} // 请求耗时（毫秒）
	CreateTime  *gtime.Time // 操作时间
	UserAgent   interface{} // user-agent用户代理
}
