// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScheduleJob is the golang structure of table schedule_job for DAO operations like Where/Data.
type ScheduleJob struct {
	g.Meta     `orm:"table:schedule_job, do:true"`
	JobId      interface{} // 任务id
	BeanName   interface{} // spring bean名称
	MethodName interface{} // 方法名
	Params     interface{} // 参数
	Cron       interface{} // cron表达式
	Status     interface{} // 任务状态
	Remark     interface{} // 备注
	CreateTime *gtime.Time // 创建时间
}
