// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ScheduleJobLog is the golang structure of table schedule_job_log for DAO operations like Where/Data.
type ScheduleJobLog struct {
	g.Meta     `orm:"table:schedule_job_log, do:true"`
	LogId      interface{} // 任务日志id
	JobId      interface{} // 任务id
	BeanName   interface{} // spring bean名称
	MethodName interface{} // 方法名
	Params     interface{} // 参数
	Status     interface{} // 任务执行结果
	Error      interface{} // 异常信息
	Times      interface{} // 耗时（单位：毫秒）
	CreateTime *gtime.Time // 创建时间
}
