// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} //
	Username   interface{} // 用户名
	Password   interface{} // 密码
	Nickname   interface{} // 昵称
	Avatar     interface{} // 头像地址
	Email      interface{} // 邮箱
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	Role       interface{} // 角色访问权限
}
