// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// VisitLog is the golang structure of table visit_log for DAO operations like Where/Data.
type VisitLog struct {
	g.Meta     `orm:"table:visit_log, do:true"`
	Id         interface{} //
	Uuid       interface{} // 访客标识码
	Uri        interface{} // 请求接口
	Method     interface{} // 请求方式
	Param      interface{} // 请求参数
	Behavior   interface{} // 访问行为
	Content    interface{} // 访问内容
	Remark     interface{} // 备注
	Ip         interface{} // ip
	IpSource   interface{} // ip来源
	Os         interface{} // 操作系统
	Browser    interface{} // 浏览器
	Times      interface{} // 请求耗时（毫秒）
	CreateTime *gtime.Time // 访问时间
	UserAgent  interface{} // user-agent用户代理
}
