// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AboutDao is the data access object for table about.
type AboutDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns AboutColumns // columns contains all the column names of Table for convenient usage.
}

// AboutColumns defines and stores column names for table about.
type AboutColumns struct {
	Id     string //
	NameEn string //
	NameZh string //
	Value  string //
}

//  aboutColumns holds the columns for table about.
var aboutColumns = AboutColumns{
	Id:     "id",
	NameEn: "name_en",
	NameZh: "name_zh",
	Value:  "value",
}

// NewAboutDao creates and returns a new DAO object for table data access.
func NewAboutDao() *AboutDao {
	return &AboutDao{
		group:   "default",
		table:   "about",
		columns: aboutColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AboutDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AboutDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *AboutDao) Columns() AboutColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *AboutDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AboutDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AboutDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
