// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlogTagDao is the data access object for table blog_tag.
type BlogTagDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns BlogTagColumns // columns contains all the column names of Table for convenient usage.
}

// BlogTagColumns defines and stores column names for table blog_tag.
type BlogTagColumns struct {
	BlogId string //
	TagId  string //
}

//  blogTagColumns holds the columns for table blog_tag.
var blogTagColumns = BlogTagColumns{
	BlogId: "blog_id",
	TagId:  "tag_id",
}

// NewBlogTagDao creates and returns a new DAO object for table data access.
func NewBlogTagDao() *BlogTagDao {
	return &BlogTagDao{
		group:   "default",
		table:   "blog_tag",
		columns: blogTagColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlogTagDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlogTagDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlogTagDao) Columns() BlogTagColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlogTagDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlogTagDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlogTagDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
