// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ExceptionLogDao is the data access object for table exception_log.
type ExceptionLogDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns ExceptionLogColumns // columns contains all the column names of Table for convenient usage.
}

// ExceptionLogColumns defines and stores column names for table exception_log.
type ExceptionLogColumns struct {
	Id          string //
	Uri         string // 请求接口
	Method      string // 请求方式
	Param       string // 请求参数
	Description string // 操作描述
	Error       string // 异常信息
	Ip          string // ip
	IpSource    string // ip来源
	Os          string // 操作系统
	Browser     string // 浏览器
	CreateTime  string // 操作时间
	UserAgent   string // user-agent用户代理
}

//  exceptionLogColumns holds the columns for table exception_log.
var exceptionLogColumns = ExceptionLogColumns{
	Id:          "id",
	Uri:         "uri",
	Method:      "method",
	Param:       "param",
	Description: "description",
	Error:       "error",
	Ip:          "ip",
	IpSource:    "ip_source",
	Os:          "os",
	Browser:     "browser",
	CreateTime:  "create_time",
	UserAgent:   "user_agent",
}

// NewExceptionLogDao creates and returns a new DAO object for table data access.
func NewExceptionLogDao() *ExceptionLogDao {
	return &ExceptionLogDao{
		group:   "default",
		table:   "exception_log",
		columns: exceptionLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ExceptionLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ExceptionLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ExceptionLogDao) Columns() ExceptionLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ExceptionLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ExceptionLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ExceptionLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
