// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FriendDao is the data access object for table friend.
type FriendDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns FriendColumns // columns contains all the column names of Table for convenient usage.
}

// FriendColumns defines and stores column names for table friend.
type FriendColumns struct {
	Id          string //
	Nickname    string // 昵称
	Description string // 描述
	Website     string // 站点
	Avatar      string // 头像
	IsPublished string // 公开或隐藏
	Views       string // 点击次数
	CreateTime  string // 创建时间
}

//  friendColumns holds the columns for table friend.
var friendColumns = FriendColumns{
	Id:          "id",
	Nickname:    "nickname",
	Description: "description",
	Website:     "website",
	Avatar:      "avatar",
	IsPublished: "is_published",
	Views:       "views",
	CreateTime:  "create_time",
}

// NewFriendDao creates and returns a new DAO object for table data access.
func NewFriendDao() *FriendDao {
	return &FriendDao{
		group:   "default",
		table:   "friend",
		columns: friendColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FriendDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FriendDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *FriendDao) Columns() FriendColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *FriendDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FriendDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FriendDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
