// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ScheduleJobLogDao is the data access object for table schedule_job_log.
type ScheduleJobLogDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns ScheduleJobLogColumns // columns contains all the column names of Table for convenient usage.
}

// ScheduleJobLogColumns defines and stores column names for table schedule_job_log.
type ScheduleJobLogColumns struct {
	LogId      string // 任务日志id
	JobId      string // 任务id
	BeanName   string // spring bean名称
	MethodName string // 方法名
	Params     string // 参数
	Status     string // 任务执行结果
	Error      string // 异常信息
	Times      string // 耗时（单位：毫秒）
	CreateTime string // 创建时间
}

//  scheduleJobLogColumns holds the columns for table schedule_job_log.
var scheduleJobLogColumns = ScheduleJobLogColumns{
	LogId:      "log_id",
	JobId:      "job_id",
	BeanName:   "bean_name",
	MethodName: "method_name",
	Params:     "params",
	Status:     "status",
	Error:      "error",
	Times:      "times",
	CreateTime: "create_time",
}

// NewScheduleJobLogDao creates and returns a new DAO object for table data access.
func NewScheduleJobLogDao() *ScheduleJobLogDao {
	return &ScheduleJobLogDao{
		group:   "default",
		table:   "schedule_job_log",
		columns: scheduleJobLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ScheduleJobLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ScheduleJobLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ScheduleJobLogDao) Columns() ScheduleJobLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ScheduleJobLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ScheduleJobLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ScheduleJobLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
