// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SiteSettingDao is the data access object for table site_setting.
type SiteSettingDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns SiteSettingColumns // columns contains all the column names of Table for convenient usage.
}

// SiteSettingColumns defines and stores column names for table site_setting.
type SiteSettingColumns struct {
	Id     string //
	NameEn string //
	NameZh string //
	Value  string //
	Type   string // 1基础设置，2页脚徽标，3资料卡，4友链信息
}

//  siteSettingColumns holds the columns for table site_setting.
var siteSettingColumns = SiteSettingColumns{
	Id:     "id",
	NameEn: "name_en",
	NameZh: "name_zh",
	Value:  "value",
	Type:   "type",
}

// NewSiteSettingDao creates and returns a new DAO object for table data access.
func NewSiteSettingDao() *SiteSettingDao {
	return &SiteSettingDao{
		group:   "default",
		table:   "site_setting",
		columns: siteSettingColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SiteSettingDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SiteSettingDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SiteSettingDao) Columns() SiteSettingColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SiteSettingDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SiteSettingDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SiteSettingDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
