// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IBlog interface {
		GetBlogCount(ctx context.Context) (count int64)
		GetBlogCountByTagId(ctx context.Context, TagId int64) (count int64)
		GetBlogCountByCategoryId(ctx context.Context, CategoryID int64) (count int64)
	}
)

var (
	localBlog IBlog
)

func Blog() IBlog {
	if localBlog == nil {
		panic("implement not found for interface IBlog, forgot register?")
	}
	return localBlog
}

func RegisterBlog(i IBlog) {
	localBlog = i
}
