// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"blog-api/internal/model"
	"blog-api/internal/model/entity"
	"context"
)

type (
	ICategory interface {
		GetCategoryList(ctx context.Context) (res []*entity.Category, err error)
		DashboardCategoryStatistics(ctx context.Context) (res *model.DashboardCategoryOutput, err error)
	}
)

var (
	localCategory ICategory
)

func Category() ICategory {
	if localCategory == nil {
		panic("implement not found for interface ICategory, forgot register?")
	}
	return localCategory
}

func RegisterCategory(i ICategory) {
	localCategory = i
}
