// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"blog-api/internal/model/entity"
	"context"
)

type ICategory interface {
	GetCategoryList(ctx context.Context) (res []*entity.Category, err error)
	DashboardCategoryStatistics(ctx context.Context) (res *model.DashboardCategoryOutput, err error)
	CreateCategory(ctx context.Context, CategoryName string) (err error)
	GetCategoryPageList(ctx context.Context, page model.PageInput) (res *model.GteCategoryListOutPut, err error)
	UpdateCategory(ctx context.Context, CategoryId int, CategoryName string) (err error)
	DeleteCategory(ctx context.Context, CategoryId int) (err error)
}

var localCategory ICategory

func Category() ICategory {
	if localCategory == nil {
		panic("implement not found for interface ICategory, forgot register?")
	}
	return localCategory
}

func RegisterCategory(i ICategory) {
	localCategory = i
}
