// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"
)

type IComment interface {
	GetCommentCount(ctx context.Context) (count int64)
	GetCommentList(ctx context.Context, page model.PageInput) (res *model.GetCommentListOutput, err error)
	UpdateCommentNotice(ctx context.Context, CommentId int, NoticeStatus bool) (err error)
	UpdateCommentPublish(ctx context.Context, CommentId int, PublishStatus bool) (err error)
}

var localComment IComment

func Comment() IComment {
	if localComment == nil {
		panic("implement not found for interface IComment, forgot register?")
	}
	return localComment
}

func RegisterComment(i IComment) {
	localComment = i
}
