// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"
)

type IFriend interface {
	GetFriendInfo(ctx context.Context) (res *model.GetFriendInfoOutput, err error)
	UpdateFriendInfo(ctx context.Context, Content string) (err error)
	GetFriendList(ctx context.Context, page model.PageInput) (res *model.GetFriendListOutput, err error)
	UpdateFriendPublishStatus(ctx context.Context, FriendId int, PublishStatus bool) (err error)
	UpdateFriend(ctx context.Context, in *model.UpdateFriendInput) (err error)
	CreateFriend(ctx context.Context, in *model.CreateFriendInput) (err error)
	UpdateCommentEnabled(ctx context.Context, CommentEnabled bool) (err error)
}

var localFriend IFriend

func Friend() IFriend {
	if localFriend == nil {
		panic("implement not found for interface IFriend, forgot register?")
	}
	return localFriend
}

func RegisterFriend(i IFriend) {
	localFriend = i
}
