// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"
)

type IJob interface {
	CreateCronJob(ctx context.Context, in *model.CreateCronJobInput) (err error)
	GetCronJobList(ctx context.Context, page model.PageInput) (res *model.GetCronJobListOutput, err error)
	UpdateJobStatus(ctx context.Context, JobId int, JobStatus bool) (err error)
	UpdateJob(ctx context.Context, in *model.UpdateJobInput) (err error)
	DeleteJob(ctx context.Context, JobId int) (err error)
	DryRunJob(ctx context.Context, JobId int) (err error)
	SyncBlogViewsToDatabase(ctx context.Context, JobId string, Param string) (err error)
	SyncVisitInfoToDatabase(ctx context.Context, JobId string, Param string) (err error)
	AddJobRecordLog(ctx context.Context, in *model.AddJobRecordLogInput) (err error)
	InitCronJob(ctx context.Context) (err error)
}

var localJob IJob

func Job() IJob {
	if localJob == nil {
		panic("implement not found for interface IJob, forgot register?")
	}
	return localJob
}

func RegisterJob(i IJob) {
	localJob = i
}
