// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"

	"github.com/gogf/gf/v2/os/gtime"
)

type ILog interface {
	GetJobLogList(ctx context.Context, page model.PageInput, startTime *gtime.Time, endTime *gtime.Time) (res *model.GetJobLogListOutput, err error)
	DeleteJobLog(ctx context.Context, LogId int) (err error)
	GetLoginLogList(ctx context.Context, page model.PageInput, startTime *gtime.Time, endTime *gtime.Time) (res *model.GetLoginLogListOutput, err error)
	DeleteLoginLog(ctx context.Context, LogId int) (err error)
	GetOperationLogList(ctx context.Context, page model.PageInput, startTime *gtime.Time, endTime *gtime.Time) (res *model.GetOperationLogListOutput, err error)
	DeleteOperationLog(ctx context.Context, LogId int) (err error)
	GetExceptionLogList(ctx context.Context, page model.PageInput, startTime *gtime.Time, endTime *gtime.Time) (res *model.GetExceptionLogListOutput, err error)
	DeleteExceptionLog(ctx context.Context, LogId int) (err error)
	GetVisitLogList(ctx context.Context, page model.PageInput, startTime *gtime.Time, endTime *gtime.Time, VisitorId string) (res *model.GetVisitLogListOutput, err error)
	DeleteVisitLog(ctx context.Context, LogId int) (err error)
}

var localLog ILog

func Log() ILog {
	if localLog == nil {
		panic("implement not found for interface ILog, forgot register?")
	}
	return localLog
}

func RegisterLog(i ILog) {
	localLog = i
}
