// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"
)

type IMoment interface {
	CreateMoment(ctx context.Context, input model.CreateMomentInput) (err error)
	GetMomentList(ctx context.Context, page model.PageInput) (res *model.GetMomentListOutput, err error)
	GetMomentDetail(ctx context.Context, MomentId int) (res *model.MomentDetailOutput, err error)
	UpdateMoment(ctx context.Context, in *model.UpdateMomentInput) error
	UpdateMomentPublished(ctx context.Context, MomentId int, IsPublished bool) (err error)
	DeleteMoment(ctx context.Context, MomentId int) (err error)
}

var localMoment IMoment

func Moment() IMoment {
	if localMoment == nil {
		panic("implement not found for interface IMoment, forgot register?")
	}
	return localMoment
}

func RegisterMoment(i IMoment) {
	localMoment = i
}
