// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"
)

type IMoment interface {
	CreateMoment(ctx context.Context, input model.CreateMomentInput) (err error)
}

var localMoment IMoment

func Moment() IMoment {
	if localMoment == nil {
		panic("implement not found for interface IMoment, forgot register?")
	}
	return localMoment
}

func RegisterMoment(i IMoment) {
	localMoment = i
}
