// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"blog-api/internal/model/entity"
	"context"
)

type ISetSetting interface {
	GetSetSetting(ctx context.Context, SetSetting string) (res []*entity.SiteSetting, err error)
	UpdateSetSetting(ctx context.Context, in *model.UpdateSetSettingInput) (err error)
}

var localSetSetting ISetSetting

func SetSetting() ISetSetting {
	if localSetSetting == nil {
		panic("implement not found for interface ISetSetting, forgot register?")
	}
	return localSetSetting
}

func RegisterSetSetting(i ISetSetting) {
	localSetSetting = i
}
