// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"blog-api/internal/model/entity"
	"context"
)

type ITag interface {
	GetTagList(ctx context.Context) (tags []*entity.Tag, err error)
	GetTagIdsByBlogId(ctx context.Context, BlogId int) (tags []*entity.BlogTag, err error)
	DashboardTagStatistics(ctx context.Context) (res *model.DashboardTagOutput, err error)
	CreateTag(ctx context.Context, in *model.CreateTagInput) (err error)
	GetTagPageList(ctx context.Context, page model.PageInput) (res *model.GetTagListOutput, err error)
	UpdateTag(ctx context.Context, in *model.UpdateTagInput) (err error)
	DeleteTag(ctx context.Context, TagId int) (err error)
}

var localTag ITag

func Tag() ITag {
	if localTag == nil {
		panic("implement not found for interface ITag, forgot register?")
	}
	return localTag
}

func RegisterTag(i ITag) {
	localTag = i
}
