// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"blog-api/internal/model/entity"
	"context"
)

type IUser interface {
	GenerateJwtToken(ctx context.Context) string
	CheckUserAccount(ctx context.Context, in model.UserAccountInput) (user *entity.User, err error)
	GetUserInfo(ctx context.Context, userId int32) (user *entity.User)
}

var localUser IUser

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
