// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"blog-api/internal/model"
	"context"
)

type IVisitor interface {
	GetTodayPvUv(ctx context.Context) (res *model.TodayPvUvOutput, err error)
	DashBoardMonthPvUvStatistics(ctx context.Context) (res *model.DashBoardMonthPvUv, err error)
	GetLatestMonthPvUv(ctx context.Context) (res []*model.LatestMonthPvUvOutput, err error)
	GetCityVisitor(ctx context.Context) (res []*model.CityVisitorOutput, err error)
	GetVisitorList(ctx context.Context, page model.PageInput) (res *model.GetVisitListOutput, err error)
	DeleteVisitor(ctx context.Context, VisitorId int) (err error)
}

var localVisitor IVisitor

func Visitor() IVisitor {
	if localVisitor == nil {
		panic("implement not found for interface IVisitor, forgot register?")
	}
	return localVisitor
}

func RegisterVisitor(i IVisitor) {
	localVisitor = i
}
