// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalAboutDao is internal type for wrapping internal DAO implements.
type internalAboutDao = *internal.AboutDao

// aboutDao is the data access object for table about.
// You can define custom methods on it to extend its functionality as you wish.
type aboutDao struct {
	internalAboutDao
}

var (
	// About is globally public accessible object for table about operations.
	About = aboutDao{
		internal.NewAboutDao(),
	}
)

// Fill with you ideas below.
