// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalBlogTagDao is internal type for wrapping internal DAO implements.
type internalBlogTagDao = *internal.BlogTagDao

// blogTagDao is the data access object for table blog_tag.
// You can define custom methods on it to extend its functionality as you wish.
type blogTagDao struct {
	internalBlogTagDao
}

var (
	// BlogTag is globally public accessible object for table blog_tag operations.
	BlogTag = blogTagDao{
		internal.NewBlogTagDao(),
	}
)

// Fill with you ideas below.
