// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalFriendDao is internal type for wrapping internal DAO implements.
type internalFriendDao = *internal.FriendDao

// friendDao is the data access object for table friend.
// You can define custom methods on it to extend its functionality as you wish.
type friendDao struct {
	internalFriendDao
}

var (
	// Friend is globally public accessible object for table friend operations.
	Friend = friendDao{
		internal.NewFriendDao(),
	}
)

// Fill with you ideas below.
