// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalScheduleJobLogDao is internal type for wrapping internal DAO implements.
type internalScheduleJobLogDao = *internal.ScheduleJobLogDao

// scheduleJobLogDao is the data access object for table schedule_job_log.
// You can define custom methods on it to extend its functionality as you wish.
type scheduleJobLogDao struct {
	internalScheduleJobLogDao
}

var (
	// ScheduleJobLog is globally public accessible object for table schedule_job_log operations.
	ScheduleJobLog = scheduleJobLogDao{
		internal.NewScheduleJobLogDao(),
	}
)

// Fill with you ideas below.
