// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalSiteSettingDao is internal type for wrapping internal DAO implements.
type internalSiteSettingDao = *internal.SiteSettingDao

// siteSettingDao is the data access object for table site_setting.
// You can define custom methods on it to extend its functionality as you wish.
type siteSettingDao struct {
	internalSiteSettingDao
}

var (
	// SiteSetting is globally public accessible object for table site_setting operations.
	SiteSetting = siteSettingDao{
		internal.NewSiteSettingDao(),
	}
)

// Fill with you ideas below.
