// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalVisitorDao is internal type for wrapping internal DAO implements.
type internalVisitorDao = *internal.VisitorDao

// visitorDao is the data access object for table visitor.
// You can define custom methods on it to extend its functionality as you wish.
type visitorDao struct {
	internalVisitorDao
}

var (
	// Visitor is globally public accessible object for table visitor operations.
	Visitor = visitorDao{
		internal.NewVisitorDao(),
	}
)

// Fill with you ideas below.
