// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-api/internal/dao/internal"
)

// internalVisitRecordDao is internal type for wrapping internal DAO implements.
type internalVisitRecordDao = *internal.VisitRecordDao

// visitRecordDao is the data access object for table visit_record.
// You can define custom methods on it to extend its functionality as you wish.
type visitRecordDao struct {
	internalVisitRecordDao
}

var (
	// VisitRecord is globally public accessible object for table visit_record operations.
	VisitRecord = visitRecordDao{
		internal.NewVisitRecordDao(),
	}
)

// Fill with you ideas below.
