// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// About is the golang structure for table about.
type About struct {
	Id     int64  `json:"id"     description:""`
	NameEn string `json:"nameEn" description:""`
	NameZh string `json:"nameZh" description:""`
	Value  string `json:"value"  description:""`
}
