// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// BlogTag is the golang structure for table blog_tag.
type BlogTag struct {
	BlogId int64 `json:"blogId" description:""`
	TagId  int64 `json:"tagId"  description:""`
}
