// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Blog is the golang structure for table blog.
type Blog struct {
	Id               int64       `json:"id"               description:""`
	Title            string      `json:"title"            description:"文章标题"`
	FirstPicture     string      `json:"firstPicture"     description:"文章首图，用于随机文章展示"`
	Content          string      `json:"content"          description:"文章正文"`
	Description      string      `json:"description"      description:"描述"`
	IsPublished      int         `json:"isPublished"      description:"公开或私密"`
	IsRecommend      int         `json:"isRecommend"      description:"推荐开关"`
	IsAppreciation   int         `json:"isAppreciation"   description:"赞赏开关"`
	IsCommentEnabled int         `json:"isCommentEnabled" description:"评论开关"`
	CreateTime       *gtime.Time `json:"createTime"       description:"创建时间"`
	UpdateTime       *gtime.Time `json:"updateTime"       description:"更新时间"`
	Views            int         `json:"views"            description:"浏览次数"`
	Words            int         `json:"words"            description:"文章字数"`
	ReadTime         int         `json:"readTime"         description:"阅读时长(分钟)"`
	CategoryId       int64       `json:"categoryId"       description:"文章分类"`
	IsTop            int         `json:"isTop"            description:"是否置顶"`
	Password         string      `json:"password"         description:"密码保护"`
	UserId           int64       `json:"userId"           description:"文章作者"`
}
