// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CityVisitor is the golang structure for table city_visitor.
type CityVisitor struct {
	City string `json:"city" description:"城市名称"`
	Uv   int    `json:"uv"   description:"独立访客数量"`
}
