// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure for table comment.
type Comment struct {
	Id              int64       `json:"id"              description:""`
	Nickname        string      `json:"nickname"        description:"昵称"`
	Email           string      `json:"email"           description:"邮箱"`
	Content         string      `json:"content"         description:"评论内容"`
	Avatar          string      `json:"avatar"          description:"头像(图片路径)"`
	CreateTime      *gtime.Time `json:"createTime"      description:"评论时间"`
	Ip              string      `json:"ip"              description:"评论者ip地址"`
	IsPublished     int         `json:"isPublished"     description:"公开或回收站"`
	IsAdminComment  int         `json:"isAdminComment"  description:"博主回复"`
	Page            int         `json:"page"            description:"0普通文章，1关于我页面，2友链页面"`
	IsNotice        int         `json:"isNotice"        description:"接收邮件提醒"`
	BlogId          int64       `json:"blogId"          description:"所属的文章"`
	ParentCommentId int64       `json:"parentCommentId" description:"父评论id，-1为根评论"`
	Website         string      `json:"website"         description:"个人网站"`
	Qq              string      `json:"qq"              description:"如果评论昵称为QQ号，则将昵称和头像置为QQ昵称和QQ头像，并将此字段置为QQ号备份"`
}
