// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Friend is the golang structure for table friend.
type Friend struct {
	Id          int64       `json:"id"          description:""`
	Nickname    string      `json:"nickname"    description:"昵称"`
	Description string      `json:"description" description:"描述"`
	Website     string      `json:"website"     description:"站点"`
	Avatar      string      `json:"avatar"      description:"头像"`
	IsPublished int         `json:"isPublished" description:"公开或隐藏"`
	Views       int         `json:"views"       description:"点击次数"`
	CreateTime  *gtime.Time `json:"createTime"  description:"创建时间"`
}
