// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// LoginLog is the golang structure for table login_log.
type LoginLog struct {
	Id          int64       `json:"id"          description:""`
	Username    string      `json:"username"    description:"用户名称"`
	Ip          string      `json:"ip"          description:"ip"`
	IpSource    string      `json:"ipSource"    description:"ip来源"`
	Os          string      `json:"os"          description:"操作系统"`
	Browser     string      `json:"browser"     description:"浏览器"`
	Status      int         `json:"status"      description:"登录状态"`
	Description string      `json:"description" description:"操作描述"`
	CreateTime  *gtime.Time `json:"createTime"  description:"登录时间"`
	UserAgent   string      `json:"userAgent"   description:"user-agent用户代理"`
}
