// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ScheduleJob is the golang structure for table schedule_job.
type ScheduleJob struct {
	JobId      int64       `json:"jobId"      description:"任务id"`
	BeanName   string      `json:"beanName"   description:"spring bean名称"`
	MethodName string      `json:"methodName" description:"方法名"`
	Params     string      `json:"params"     description:"参数"`
	Cron       string      `json:"cron"       description:"cron表达式"`
	Status     int         `json:"status"     description:"任务状态"`
	Remark     string      `json:"remark"     description:"备注"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
}
