// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SiteSetting is the golang structure for table site_setting.
type SiteSetting struct {
	Id     int64  `json:"id"     description:""`
	NameEn string `json:"nameEn" description:""`
	NameZh string `json:"nameZh" description:""`
	Value  string `json:"value"  description:""`
	Type   int    `json:"type"   description:"1基础设置，2页脚徽标，3资料卡，4友链信息"`
}
