// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int64       `json:"id"         description:""`
	Username   string      `json:"username"   description:"用户名"`
	Password   string      `json:"password"   description:"密码"`
	Nickname   string      `json:"nickname"   description:"昵称"`
	Avatar     string      `json:"avatar"     description:"头像地址"`
	Email      string      `json:"email"      description:"邮箱"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	Role       string      `json:"role"       description:"角色访问权限"`
}
