// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Visitor is the golang structure for table visitor.
type Visitor struct {
	Id         int64       `json:"id"         description:""`
	Uuid       string      `json:"uuid"       description:"访客标识码"`
	Ip         string      `json:"ip"         description:"ip"`
	IpSource   string      `json:"ipSource"   description:"ip来源"`
	Os         string      `json:"os"         description:"操作系统"`
	Browser    string      `json:"browser"    description:"浏览器"`
	CreateTime *gtime.Time `json:"createTime" description:"首次访问时间"`
	LastTime   *gtime.Time `json:"lastTime"   description:"最后访问时间"`
	Pv         int         `json:"pv"         description:"访问页数统计"`
	UserAgent  string      `json:"userAgent"  description:"user-agent用户代理"`
}
