// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VisitLog is the golang structure for table visit_log.
type VisitLog struct {
	Id         int64       `json:"id"         description:""`
	Uuid       string      `json:"uuid"       description:"访客标识码"`
	Uri        string      `json:"uri"        description:"请求接口"`
	Method     string      `json:"method"     description:"请求方式"`
	Param      string      `json:"param"      description:"请求参数"`
	Behavior   string      `json:"behavior"   description:"访问行为"`
	Content    string      `json:"content"    description:"访问内容"`
	Remark     string      `json:"remark"     description:"备注"`
	Ip         string      `json:"ip"         description:"ip"`
	IpSource   string      `json:"ipSource"   description:"ip来源"`
	Os         string      `json:"os"         description:"操作系统"`
	Browser    string      `json:"browser"    description:"浏览器"`
	Times      int         `json:"times"      description:"请求耗时（毫秒）"`
	CreateTime *gtime.Time `json:"createTime" description:"访问时间"`
	UserAgent  string      `json:"userAgent"  description:"user-agent用户代理"`
}
