// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// VisitRecord is the golang structure for table visit_record.
type VisitRecord struct {
	Id   int64  `json:"id"   description:""`
	Pv   int    `json:"pv"   description:"访问量"`
	Uv   int    `json:"uv"   description:"独立用户"`
	Date string `json:"date" description:"日期\"02-23\""`
}
